name: Build Library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-action
      - uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: auth_plugin_pyauth.so